### ISSUE TITLE
UI improve of home page 

### ISSUE THREAD

**Issue by biswajit-sarkar-007** [pranshu05/tunestats#7]
in your website in home page the `Why TuneStats?` this section the cards are not good in ui there should be implement some animation and hover effect to it to look more amazing its 

![WhatsApp Image 2024-12-13 at 13 07 16_f11480d3](https://github.com/user-attachments/assets/6fabbe21-bcb4-4d3f-83cd-b844a5c7f9d2)

**Comment by SHRUTISINHA250714** [comment]
Hi, I'd like to take up this issue. I plan to add some animations and hover effects to improve the UI of the cards. Could you please assign it to me?

**Comment by pranshu05** [comment]
@SHRUTISINHA250714 done
